import Carousel from '@/components/Carousel';
import MainNav from '@/components/Navbar/MainNav';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Kilabyte</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <MainNav />
      <div className="h-screen bg-[#282626] ">
        <div className="container mx-auto">
          <div className="w-2/3 py-32">
            <h1 className="text-xs text-[#7E7E7E] tracking-widest  mb-8">
              <span className="text-transparent bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">FULL-SERVICE</span> ECOMMERCE AGENCY
            </h1>
            <p className="text-5xl text-[#ffffff] mb-16">The enterprise eCommerce agency for design-conscious B2B and D2C brands.</p>
            <button type="button" className="text-black bg-[#fff] hover:bg-black focus:outline-[#fff] rounded-full py-3 px-5">
              <a className="py-5 px-3 text-xs font-bold">OUR WORK</a>
            </button>
          </div>
        </div>
      </div>
      <Carousel />
    </>
  );
}
